origin_prefixes:
    github_mm: 'git@github.com:machines-in-motion/'
    github_odri: 'git@github.com:open-dynamic-robot-initiative/'
    git-pybind: 'git@github.com:pybind/'
    git-loco3d: 'git@gepgitlab.laas.fr:loco-3d/'
    https-pybind: 'https://github.com/pybind/'
    https-sot: 'https://github.com/stack-of-tasks/'
    https-hpp: 'https://github.com/humanoid-path-planner/'
    https-gepetto: 'https://github.com/gepetto/'
    https-laas: 'https://github.com/laas/'
    https-jrl-umi3218: 'https://github.com/jrl-umi3218/'
